import type {Metadata} from 'next'
import './globals.css'
import {AuthProvider} from "@/context/authProvider";
import {UIProvider} from '@/context/uiProvider';
import ToastContainerWrapper from "@/components/common/notifications/ToastComponent";

export const metadata: Metadata = {
    title: 'Admin Panel',
    description: 'Generated by upsert next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <UIProvider>
            <AuthProvider>
                <ToastContainerWrapper/>
                {children}
            </AuthProvider>
        </UIProvider>
        </body>
        </html>
    )
}
